version: "3.8"

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    networks:
      - webnet

networks:
  webnet:
